name: "install-poetry"
description: "Composite action to setup the Python enviroment and install poetry"

inputs:
  python-version:
    required: false
    description: "The python version to use"
    default: "{{cookiecutter.target_python_version}}"
  poetry-version:
    required: false
    description: "The poetry version to use"
    default: "{{cookiecutter.poetry_version}}"
  working-directory:
    required: false
    description: "The working directory where create the venv"
    default: "."

runs:
  using: "composite"
  steps:
  - name: Set up python
    uses: actions/setup-python@v5
    with:
      python-version: {% raw %}${{ inputs.python-version }}{% endraw %}

  - name: Install Poetry
    working-directory: {% raw %}${{ inputs.working-directory }}{% endraw %}
    run: |
      python -m pip install --upgrade pip
      pip install poetry=={% raw %}${{ inputs.poetry-version }}{% endraw %}
      poetry config virtualenvs.create true
      poetry config virtualenvs.in-project true
      poetry config virtualenvs.prefer-active-python true
    shell: bash
