repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: ['--unsafe']
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/python-poetry/poetry
    rev: '{{cookiecutter.poetry_version}}'
    hooks:
    - id: poetry-check
      args: ['--lock']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.2"
    hooks:
      - id: ruff
        args: [ --fix ]

  - repo: https://github.com/psf/black
    rev: "23.12.1"
    hooks:
      - id: black
        args:
          - --preview

{%- if cookiecutter.mkdocs == 'y' %}

  - repo: https://github.com/PyCQA/docformatter
    rev: "v1.7.5"
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --config, ./pyproject.toml]
{%- endif %}

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
