name: Pull Request - Workflow
run-name: Pull request from {% raw %}${{ github.event.pull_request.head.ref }}{% endraw %}

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '*.md'

env:
  PYTHON_VERSION: "{{cookiecutter.target_python_version}}"
  POETRY_VERSION: "{{cookiecutter.poetry_version}}"

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        id: setup-environment
        uses: ga-data-strategy-analytics/ga-github-workflows/.github/actions/setup-poetry-env@main
        with:
          python-version: {% raw %}${{ env.PYTHON_VERSION }}{% endraw %}
          poetry-version: {% raw %}${{ env.POETRY_VERSION }}{% endraw %}

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: {% raw %}pre-commit-${{ runner.os }}-${{ steps.setup-environment.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}{% endraw %}

      - name: Run quality checks
        run: make check
{% if cookiecutter.tox == 'y' %}
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up python & install poetry
        id: setup-python-poetry
        uses: ga-data-strategy-analytics/ga-github-workflows/.github/actions/install-poetry@main
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
          poetry-version: {% raw %}${{ env.POETRY_VERSION  }}{% endraw %}

      - name: Load cached venv
        uses: actions/cache@v4
        with:
          path: .tox
          key: {% raw %}venv-${{ runner.os }}-${{ matrix.python-version }}-${{ env.POETRY_VERSION }}-${{ hashFiles('poetry.lock') }}{% endraw %}

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      - name: Test with tox
        run: tox
{% else %}
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ga-data-strategy-analytics/ga-github-workflows/.github/actions/setup-poetry-env@main
        with:
          python-version: {% raw %}${{ env.PYTHON_VERSION }}{% endraw %}
          poetry-version: {% raw %}${{ env.POETRY_VERSION }}{% endraw %}

      - name: Run tests
        run: make test
{%- endif %}

{%- if cookiecutter.mkdocs == "y" %}
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ga-data-strategy-analytics/ga-github-workflows/.github/actions/setup-poetry-env@main
        with:
            python-version: {% raw %}${{ env.PYTHON_VERSION }}{% endraw %}
            poetry-version: {% raw %}${{ env.POETRY_VERSION }}{% endraw %}

      - name: Check if documentation can be built
        run: make docs-test
{%- endif %}
