name: "setup-poetry-env"
description: "Composite action to setup the Python and poetry environment."

inputs:
  python-version:
    required: false
    description: "The python version to use"
    default: "{{cookiecutter.target_python_version}}"
  poetry-version:
    required: false
    description: "The poetry version to use"
    default: "{{cookiecutter.poetry_version}}"
  poetry-root-path:
    required: false
    description: "The path of the poetry project containing pyproject.toml and all python file"
    default: "."

runs:
  using: "composite"
  steps:
  - name: Set up python & install poetry
    uses: ./.github/actions/install-poetry
    with:
      python-version: {% raw %}${{ inputs.python-version }}{% endraw %}
      poetry-version: {% raw %}${{ inputs.poetry-version }}{% endraw %}

  - name: Load cached venv
    id: cached-poetry-dependencies
    uses: actions/cache@v4
    env:
      POETRY_LOCK_PATH: {% raw %}${{ inputs.poetry-root-path }}/poetry.lock${% endraw %}
    with:
      path: {% raw %}${{ inputs.poetry-root-path }}/.venv{% endraw %}
      key: {% raw %}venv-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.poetry-version }}-${{ hashFiles(env.POETRY_LOCK_PATH) }}{% endraw %}

  - name: Install dependencies
    if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    working-directory: {% raw %}${{ inputs.poetry-root-path }}{% endraw %}
    run: |
      poetry install --no-interaction
    shell: bash
